### ISSUE TITLE
import uic fail, quick-fix

### ISSUE THREAD

**Issue by aztecman** [KnowZero/Krita-PythonPluginDeveloperTools#5]
I get a error on the plugin generator file that it can't find "uic"

quick fix: replace "import uic" with
"from PyQt5 import uic"

**Comment by KnowZero** [comment]
Fixed, thanks

**Comment by zerobikappa** [comment]
Still failed to load the plugin in Windows11. Please also emend this line:

https://github.com/KnowZero/Krita-PythonPluginDeveloperTools/blob/001136b58458179e4d39b5d3e639df93926a1fe9/plugindevtools/PluginDevTools/PluginGenerator.py#L2

**Comment by KnowZero** [comment]
Okay, fixed
